config/routes.rb
Rails.application.routes.draw do
  root :to => 'search#form'

  get 'search' => 'search#form'
  post 'search/form'
  get 'search/form'
  post 'search/show'
  get 'search/show' => 'search#form'
  post 'search/detail'
  get 'search/detail' => 'search#form'
  post 'search/logout'
  get 'search/logout' => 'search#form'

  get '/users/login' => 'users#login'
  post '/users/auth' => 'users#auth'
  get '/users/new' => 'users#new'
  post '/users/edit' => 'users#edit'
  post '/users/update' => 'users#update'
  delete '/users/destroy/:id' => 'users#destroy'
  get  '/users/avaliable/:link_pass' => 'users#avaliable'
  post '/users/confirm' => 'users#confirm'
  post '/users/complete' => 'users#complete'

  get '/inc_accounts/login' => 'inc_accounts#login'
  get '/inc_accounts/new' => 'inc_accounts#new'
  post '/inc_accounts/edit' => 'inc_accounts#edit'
  post '/inc_accounts/update' => 'inc_accounts#update'
  delete '/inc_accounts/destroy/:id' => 'inc_accounts#destroy'
  post '/inc_accounts/auth' => 'inc_accounts#auth'
  post '/inc_accounts/logout' => 'inc_accounts#logout'
  get  '/inc_accounts/avaliable/:link_pass' => 'inc_accounts#avaliable'
  post '/inc_accounts/confirm' => 'inc_accounts#confirm'
  post '/inc_accounts/complete' => 'inc_accounts#complete'

  get '/housing_databases/showTables/:id' => 'housing_databases#showTables', as: 'housing_databases_showTables'
 get '/housing_databases/registerDatabases/:id' => 'housing_databases#registerDatabases', as: 'housing_databases_registerDatabases'
 get '/housing_databases/detail/:id' => 'housing_databases#detail', as: 'housing_databases_detail'
 get '/housing_databases/editDatabases/:id' => 'housing_databases#editDatabases',as: 'housing_databases_editDatabases'
 get '/housing_databases/:id/image/' => 'housing_databases#image',as: 'housing_databases_image'
 post '/housing_databases/registerDatabases/:id' => 'housing_databases#create'
 patch '/housing_databases/editDatabases/:id' => 'housing_databases#update'
 delete '/housing_databases/details/:id' => 'housing_databases#destroy',as:'housing_databases_destroy'

 get '/advertising_databases/showTables/:id' => 'advertising_databases#showTables',as:'advertising_databases_showTables'
 get '/advertising_databases/registerDatabases/:id' => 'advertising_databases#registerDatabases',as:'advertising_databases_registerDatabses'
 get '/advertising_databases/details/:id' => 'advertising_databases#details', as: 'advertising_databases_details'
 get '/advertising_databases/editDatabases/:id' => 'advertising_databases#editDatabases',as: 'advertising_databases_editDatabases'
 get '/advertising_databases/:id/image/' => 'advertising_databases#image',as: 'advertising_databases_image'
 post '/advertising_databases/registerDatabases/:id' => 'advertising_databases#create'
 patch '/advertising_databases/editDatabases/:id' => 'advertising_databases#update'
 delete '/advertising_databases/showTables/:id' => 'advertising_databases#destroy',as:'advertising_databases_destroy'

  get '/store/registerStores/:id' => 'store#registerStores',as: 'registerStores'
  get '/store/showStores/:id' => 'store#showStores',as:'showStores'
  get '/store/editStores/:id' => 'store#editStores',as:'editStores'
  post '/store/registerStores/:id' => 'store#create'
  patch '/store/editStores/:id' => 'store#update'
  delete '/store/showStores/:id' => 'store#destroy',as:'store_destroy'

  resources :search do
    member { get :image }
  end
  resources :advertising_databases do
      member do
        get 'show_image'
      end
  end

end

app/controllers/housing_databases_controller.rb
############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################

class HousingDatabasesController < DatabasesController

  # 一覧表示を行う
  def showTables
    @housing = Housing.new
    @inc = IncAccount.find(params[:id])
    @store = @inc.Store
    @inc_account_id = params[:id]
    @inc_account = IncAccount.find(@inc_account_id)
    if session[@inc_account_id]==nil || session[@inc_account_id]==''
      #広告取得
      advertisings=Advertising.all
      @advertisings=[]
      if advertisings.length>0 then
          (0..1).each{|num|
              @advertisings[num]=advertisings[rand(0..advertisings.length-1)]
          }
      end
      render :template => "search/form"
    end
    @housing = Housing.where(inc_account_id: @inc_account_id)
  end

  # 画像の表示に必要なデータをとりだし、send_dataで送信している
  def image
    @housing = Housing.find(params[:id])
    send_data(@housing.image, :type => 'image/jpeg', disposition: :inline)
  end

  # 登録ページの表示を行っている
  def registerDatabases
    @inc_account_id = params[:id]
    @inc = IncAccount.find(params[:id])
    @store = @inc.Store
    @housing = Housing.new
    @housingdate = Date.new(1950, 1, 1)
    @facilities = Facility.all
  end

  # 編集ページの表示を行っている
  def editDatabases
    @housing = Housing.find(params[:id])
    @inc = IncAccount.find(@housing.inc_account_id)
    @store = @inc.Store
  end

  # 削除
  def deleteDatabases

  end

  # 詳細ページの表示を行っている
  def detail
    @housing = Housing.find(params[:id])
    @inc = IncAccount.find(@housing.inc_account_id)
    @store = Store.find(@housing.store_id)
  end

  # 登録ページにて登録ボタンが押された場合に呼び出される　データを入力してDBに登録
  def create
    if params[:store_register]
      redirect_to registerStores_path(params[:id])
    else
      @inc_account_id = params[:id]
      @inc = IncAccount.find(params[:id])
      @store = @inc.Store
      @facilities = Facility.all

      @housing = Housing.new
      @date = params[:date]
      @housingdate = DateTime.new(@date["building_date(1i)"].to_i,@date["building_date(2i)"].to_i,@date["building_date(3i)"].to_i)
      @selected = params[:selectedstore_id]

      @housing.store_id = @selected["store_id"].to_i

      #住宅情報を登録
      @housing.inc_account_id = params[:id]
      @housing.street_address = params[:street_address]
      @housing.rent = params[:rent]
      @housing.administration_cost = params[:administration_cost]
      @housing.housing_type = params[:housing_type]
      @housing.building_date = @housingdate
      @housing.direction = params[:direction]
      @housing.layout = params[:layout]
      @housing.area = params[:area]
      @housing.structure = params[:structure]
      @housing.floor = params[:floor]
      @housing.deposit = params[:deposit]
      @housing.recompense = params[:recompense]
      @housing.security_money = params[:security_money]
      @housing.shikibiki = params[:shikibiki]
      @housing.insurance = params[:insurance]

      if params[:parking].present?
        @housing.parking = params[:parking]
      else
        @housing.parking = -1
      end

      @housing.trading_aspect = params[:trading_aspect]
      @housing.another_cost = params[:another_cost]
      @housing.vacancy = params[:vacancy]
      @housing.detail = params[:detail]
      @housing.plan = params[:plan]
      @housing.views = 0
      @housing.favorites = 0

      if params[:image].present?
        @housing.image = params[:image].read
      end

      if @housing.save
        #距離情報を登録
        distances = params[:distance]
        housing_id = Housing.last.id
        store_id = @selected["store_id"].to_i
        facilities = Facility.all
        facilities.each{|facility|
          distance = Distance.new
          distance.distance = distances[facility.id.to_s]
          distance.facility_id = facility.id
          distance.housing_id = housing_id
          distance.store_id = store_id
          distance.inc_account_id = params[:id]
          distance.save
        }
        redirect_to housing_databases_showTables_path(params[:id]), notice: "住宅情報を登録しました"
      else
        @date = nil
        render action: "registerDatabases"
      end
    end

  end

  #編集ページにて編集ボタンが押された場合に呼び出される　編集元データを取得、及び更新
  def update
    if params[:store_register]
      redirect_to registerStores_path(params[:id])
    else
      @housing = Housing.find(params[:id])
      @date = params[:date]
      @housingdate = DateTime.new(@date["building_date(1i)"].to_i,@date["building_date(2i)"].to_i,@date["building_date(3i)"].to_i)
      @selected = params[:selectedstore_id]
      @selectedplans = params[:selectedplan]
      @inc = IncAccount.find(@housing.inc_account_id)
      @store = @inc.Store

      @housing.store_id = @selected["store_id"].to_i
      @housing.street_address = params[:street_address]
      @housing.rent = params[:rent]
      @housing.administration_cost = params[:administration_cost]
      @housing.housing_type = params[:housing_type]
      @housing.building_date = @housingdate
      @housing.direction = params[:direction]
      @housing.layout = params[:layout]
      @housing.area = params[:area]
      @housing.structure = params[:structure]
      @housing.floor = params[:floor]
      @housing.deposit = params[:deposit]
      @housing.recompense = params[:recompense]
      @housing.security_money = params[:security_money]
      @housing.shikibiki = params[:shikibiki]
      @housing.insurance = params[:insurance]

      if params[:parking].present?
        @housing.parking = params[:parking]
      else
        @housing.parking = -1
      end

      @housing.trading_aspect = params[:trading_aspect]
      @housing.another_cost = params[:another_cost]
      @housing.vacancy = params[:vacancy]
      @housing.detail = params[:detail]
      @housing.plan = params[:plan]

      if params[:image].present?
        @housing.image = params[:image].read
      end

      if @housing.save
        redirect_to housing_databases_detail_path(params[:id]), notice: "住宅情報を登録しました"
      else
        @date = nil
        render action: "editDatabases"
      end
    end

  end

  # 削除ボタンを押した場合に呼び出される
  def destroy
    @housing = Housing.find(params[:id])
    @inc = IncAccount.find(@housing.inc_account_id)
    @housing.destroy
    redirect_to housing_databases_showTables_path(@inc.id)
  end
end

app/helpers/housing_databases_helper.rb
module HousingDatabasesHelper
end

app/views/housing_databases/detail.html.erb
<!--############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################-->

<%= render 'shared/library' %>
<%= render 'shared/incmenu' %>

<table>
  <tbody>
  <tr><td><%= image_tag(housing_databases_image_path(@housing.id), :size => '100x100') %></td></tr>
  <tr><td>店舗情報</td>  <td><%= @store.store_name%></td></tr>
  <tr><td>住所</td> <td><%= @housing.street_address%></td> </tr>
  <tr><td>家賃</td>  <td><%= @housing.rent%></td> </tr>
  <tr><td>管理費</td>  <td><%= @housing.administration_cost%></td> </tr>
  <tr><td>タイプ</td>  <td><%= @housing.housing_type%></td></tr>
  <tr><td>建築年月</td>  <td><%= @housing.building_date%></td></tr>
  <tr><td>向き</td>  <td><%= @housing.direction%></td></tr>
  <tr><td>間取り</td>  <td><%= @housing.layout%></td></tr>
  <tr><td>面積</td>  <td><%= @housing.area.to_f / 10%></td></tr>
  <tr><td>構造</td>  <td><%= @housing.structure%></td></tr>
  <tr><td>階建て</td>  <td><%= @housing.floor%></td></tr>
  <tr><td>敷金</td>  <td><%= @housing.deposit%></td></tr>
  <tr><td>礼金</td>  <td><%= @housing.recompense%></td></tr>
  <tr><td>保証金</td>  <td><%= @housing.security_money%></td></tr>
  <tr><td>敷引き</td>  <td><%= @housing.shikibiki%></td></tr>
  <tr><td>保険料</td>  <td><%= @housing.insurance%></td></tr>
  <tr><td>駐車場料金</td>  <td><%= if @housing.parking == -1
                                "駐車場なし"
                              else @housing.parking
                              end%></td></tr>
  <tr><td>取引態様</td>  <td><%= @housing.trading_aspect%></td></tr>
  <tr><td>他初期費用</td>  <td><%= @housing.another_cost%></td></tr>
  <tr><td>空き部屋情報</td>  <td><%= @housing.vacancy%></td></tr>
  <tr><td>詳細情報</td>  <td><%= @housing.detail%></td></tr>
  <tr><td>契約プラン</td>  <td><%= if @housing.plan == 1
                                    "年契約"
                                    else
                                      "月契約"
                                    end%></td></tr>
  <tr><td>契約更新日</td>  <td><%= @housing.contract_update%></td></tr>
  <tr><td>閲覧数</td>  <td><%= @housing.views%></td></tr>
  <tr><td>お気に入り件数</td>  <td><%= @housing.favorites%></td></tr>

  </tbody>
</table>

<%= link_to '編集', housing_databases_editDatabases_path(@housing.id)  %>
<%= link_to '削除', housing_databases_destroy_path(@housing.id),method: 'delete',"data-confirm" => "本当に削除しますか？" %>
<%= link_to '一覧へ戻る', housing_databases_showTables_path(@housing.inc_account_id)%>

app/views/housing_databases/editDatabases.html.erb
<!--############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################-->

<%= render 'shared/library' %>
<%= render 'shared/incmenu' %>

<%= form_tag housing_databases_editDatabases_path(@housing.id), method: 'patch',multipart: true do%>
    <table>

      <tbody>
      <tr><td>画像</td> </tr>
      <tr><td><%= file_field_tag 'image',:accept => "image/png,image/gif,image/jpeg" %></td></tr>

      <tr><td>店舗選択</td>  </tr>
      <tr><td><%= collection_select(:selectedstore_id,:store_id,@store.all,:id,:store_name) %></td> <td><%= submit_tag "店舗情報新規登録" ,:name => 'store_register'%></td></tr>
      <tr><td colspan="2"><font color="red">　<%= if @store.blank?
                                                   "店舗情報がありません。登録してください" end %></font></td><tr>
      <tr><td>住所</td>  </tr>
      <tr><td><%= text_field_tag :street_address,@housing.street_address, :placeholder => "住所" %></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:street_address] %></font></td><tr>

      <tr><td>家賃（円単位、数字のみで入力）</td>   </tr>
      <tr><td><%= text_field_tag :rent,@housing.rent,:placeholder => '家賃'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:rent] %></font></td><tr>

      <tr><td>管理費（円単位、数字のみで入力）</td>   </tr>
      <tr><td><%= text_field_tag :administration_cost,@housing.administration_cost,:placeholder => '管理費'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:administration_cost] %></font></td><tr>

      <tr><td>タイプ（マンション、賃貸など）</td>  </tr>
      <tr><td><%= text_field_tag :housing_type,@housing.housing_type,:placeholder => 'タイプ'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:housing_type] %></font></td><tr>

      <tr><td>建築年月</td>  </tr>
      <tr><td><%= date_select(:date, :building_date, :use_month_numbers => true,:discard_day => true,:default => @housing.building_date,:start_year =>1950,:end_year => Time.now.year.to_i)%></td></tr>

      <tr><td>向き</td> </tr>
      <tr><td><%= text_field_tag :direction,@housing.direction,:placeholder => '向き'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:direction] %></font></td><tr>

      <tr><td>間取り</td>  </tr>
      <tr><td><%= text_field_tag :layout,@housing.layout,:placeholder => '間取り'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:layout] %></font></td><tr>

      <tr><td>面積（数字のみ）記入例：12.2平方メートルの場合は「122」と入力</td>  </tr>
      <tr><td><%= text_field_tag :area,@housing.area,:placeholder => '面積'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:area] %></font></td><tr>

      <tr><td>構造（鉄筋コンクリート、木造など）</td>  </tr>
      <tr><td><%= text_field_tag :structure,@housing.structure,:placeholder => '構造'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:structure] %></font></td><tr>

      <tr><td>階建て（数字のみ）記入例：３階建ての場合は「3」と入力</td>  </tr>
      <tr><td><%= text_field_tag :floor,@housing.floor,:placeholder => '階建て'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:floor] %></font></td><tr>

      <tr><td>敷金（円単位、数字のみで入力）</td>  </tr>
      <tr><td><%= text_field_tag :deposit,@housing.deposit,:placeholder => '敷金'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:deposit] %></font></td><tr>

      <tr><td>礼金（円単位、数字のみで入力）</td>  </tr>
      <tr><td><%= text_field_tag :recompense,@housing.recompense,:placeholder => '礼金'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:recompense] %></font></td><tr>

      <tr><td>保証金（円単位、数字のみで入力）</td>  </tr>
      <tr><td><%= text_field_tag :security_money,@housing.security_money,:placeholder => '保証金'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:security_money] %></font></td><tr>

      <tr><td>敷引き（円単位、数字のみで入力）</td>  </tr>
      <tr><td><%= text_field_tag :shikibiki,@housing.shikibiki,:placeholder => '敷引き'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:shikibiki] %></font></td><tr>

      <tr><td>保険料（円単位、数字のみで入力）</td>  </tr>
      <tr><td><%= text_field_tag :insurance,@housing.insurance,:placeholder => '保険料'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:insurance] %></font></td><tr>

      <tr><td>駐車場使用料（円単位、数字のみで入力、駐車場がない場合は未記入）</td>  </tr>
      <%= if @housing.parking == -1
            @housing.parking = nil
          end %>
      <tr><td><%= text_field_tag :parking,@housing.parking,:placeholder => '駐車場使用料'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:parking] %></font></td><tr>

      <tr><td>取引態様（仲介など）</td>  </tr>
      <tr><td><%= text_field_tag :trading_aspect,@housing.trading_aspect,:placeholder => '取引態様'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:trading_aspect] %></font></td><tr>

      <tr><td>他初期費用（円単位、数字のみで入力）</td>  </tr>
      <tr><td><%= text_field_tag :another_cost,@housing.another_cost,:placeholder => '他初期費用'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:another_cost] %></font></td><tr>

      <tr><td>空き部屋情報</td>  </tr>
      <tr><td><%= text_field_tag :vacancy,@housing.vacancy,:placeholder => '空き部屋情報'%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:vacancy] %></font></td><tr>

      <tr><td>詳細情報</td>  </tr>
      <tr><td><%= text_area_tag :detail,@housing.detail,:placeholder => '詳細情報' ,:size => "50x10"%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:detail] %></font></td><tr>

      <tr><td>契約プラン</td>  </tr>
      <tr><td><%= radio_button_tag :plan, 1 %> <%= label_tag :plan_name, "年契約" %>
        <%= radio_button_tag :plan, 2 %> <%= label_tag :plan_name, "月契約" %></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @housing.errors.messages[:plan] %></font></td><tr>
      </tbody>
    </table>

    <%= submit_tag "編集" ,"data-confirm" => "編集を行いますか？"%>
<% end %>

app/views/housing_databases/index.html.erb
<!--############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################-->

<%= render 'shared/library' %>
<%= render 'shared/menu' %>

<div class="container-fluid"><div class="row">
<div class="col-sm-1"></div>
  <div class="col-sm-10">
    <ul class="nav nav-tabs">
     <li class="active"><a href="/housing_databases/showTables/<%= @inc_account_id %>">物件</a></li>
     <li><a href="/advertising_databases/showTables/<%= @inc_account_id %>">広告</a></li>
    </ul>
  </div>
<div class="col-sm-1"></div>
</div></div>

app/views/housing_databases/showTables.html.erb
<!--############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################-->

<%= render 'shared/library' %>
<%= render 'shared/incmenu' %>

<div class="container-fluid" style="margin:20px;"><div class="row">
  <ul class="nav nav-tabs">
   <li class="active"><a href="/housing_databases/showTables/<%= @inc_account_id %>">物件</a></li>
   <li><a href="/advertising_databases/showTables/<%= @inc_account_id %>">広告</a></li>
    <li><a href="/store/showStores/<%= @inc_account_id %>">店舗</a></li>
  </ul>
  <div align="right"><%= button_to "物件登録", housing_databases_registerDatabases_path(@inc_account_id), method: :get, class: "btn btn-success", style: "margin:5px;"%></div>
  <div class="container">
    <table class="table">
      <thead>
        <tr>
        <th>イメージ</th>
        <th>住所</th>
        <th>家賃</th>
        <th>管理費</th>
        <th>タイプ</th>
        <th>建築年月</th>
        <th>向き</th>
        <th>間取り</th>
        <th>面積</th>
        <th>契約更新日</th>
      </thead>
      <tbody>
        <% @housing.each do |info| %>
        <tr>
          <td><%= image_tag(housing_databases_image_path(info.id), :size => '100x100') %></td>
          <td><%= info.street_address %></td>
          <td><%= info.rent %></td>
          <td><%= info.administration_cost %></td>
          <td><%= info.housing_type %></td>
          <td><%= info.building_date %></td>
          <td><%= info.direction %></td>
          <td><%= info.layout %></td>
          <td><%= info.area.to_f / 10%></td>
          <td><%= info.contract_update %></td>
          <td><%= button_to '詳細', housing_databases_detail_path(info.id), method: :get, class: "btn btn-warning" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div></div>