config/routes.rb
Rails.application.routes.draw do
  root :to => 'search#form'

  get 'search' => 'search#form'
  post 'search/form'
  get 'search/form'
  post 'search/show'
  get 'search/show' => 'search#form'
  post 'search/detail'
  get 'search/detail' => 'search#form'
  post 'search/logout'
  get 'search/logout' => 'search#form'

  get '/users/login' => 'users#login'
  post '/users/auth' => 'users#auth'
  get '/users/new' => 'users#new'
  post '/users/edit' => 'users#edit'
  post '/users/update' => 'users#update'
  delete '/users/destroy/:id' => 'users#destroy'
  get  '/users/avaliable/:link_pass' => 'users#avaliable'
  post '/users/confirm' => 'users#confirm'
  post '/users/complete' => 'users#complete'

  get '/inc_accounts/login' => 'inc_accounts#login'
  get '/inc_accounts/new' => 'inc_accounts#new'
  post '/inc_accounts/edit' => 'inc_accounts#edit'
  post '/inc_accounts/update' => 'inc_accounts#update'
  delete '/inc_accounts/destroy/:id' => 'inc_accounts#destroy'
  post '/inc_accounts/auth' => 'inc_accounts#auth'
  post '/inc_accounts/logout' => 'inc_accounts#logout'
  get  '/inc_accounts/avaliable/:link_pass' => 'inc_accounts#avaliable'
  post '/inc_accounts/confirm' => 'inc_accounts#confirm'
  post '/inc_accounts/complete' => 'inc_accounts#complete'

  get '/housing_databases/showTables/:id' => 'housing_databases#showTables', as: 'housing_databases_showTables'
 get '/housing_databases/registerDatabases/:id' => 'housing_databases#registerDatabases', as: 'housing_databases_registerDatabases'
 get '/housing_databases/detail/:id' => 'housing_databases#detail', as: 'housing_databases_detail'
 get '/housing_databases/editDatabases/:id' => 'housing_databases#editDatabases',as: 'housing_databases_editDatabases'
 get '/housing_databases/:id/image/' => 'housing_databases#image',as: 'housing_databases_image'
 post '/housing_databases/registerDatabases/:id' => 'housing_databases#create'
 patch '/housing_databases/editDatabases/:id' => 'housing_databases#update'
 delete '/housing_databases/details/:id' => 'housing_databases#destroy',as:'housing_databases_destroy'

 get '/advertising_databases/showTables/:id' => 'advertising_databases#showTables',as:'advertising_databases_showTables'
 get '/advertising_databases/registerDatabases/:id' => 'advertising_databases#registerDatabases',as:'advertising_databases_registerDatabses'
 get '/advertising_databases/details/:id' => 'advertising_databases#details', as: 'advertising_databases_details'
 get '/advertising_databases/editDatabases/:id' => 'advertising_databases#editDatabases',as: 'advertising_databases_editDatabases'
 get '/advertising_databases/:id/image/' => 'advertising_databases#image',as: 'advertising_databases_image'
 post '/advertising_databases/registerDatabases/:id' => 'advertising_databases#create'
 patch '/advertising_databases/editDatabases/:id' => 'advertising_databases#update'
 delete '/advertising_databases/showTables/:id' => 'advertising_databases#destroy',as:'advertising_databases_destroy'

  get '/store/registerStores/:id' => 'store#registerStores',as: 'registerStores'
  get '/store/showStores/:id' => 'store#showStores',as:'showStores'
  get '/store/editStores/:id' => 'store#editStores',as:'editStores'
  post '/store/registerStores/:id' => 'store#create'
  patch '/store/editStores/:id' => 'store#update'
  delete '/store/showStores/:id' => 'store#destroy',as:'store_destroy'

  resources :search do
    member { get :image }
  end
  resources :advertising_databases do
      member do
        get 'show_image'
      end
  end

end

app/models/advertising.rb
class Advertising < ActiveRecord::Base
  belongs_to :inc_account

  validates :advertise_info,
            length: {maximum: 50, message: "⚠︎50文字以下で入力してください" }

  validates :image,
            presence: { message: "⚠画像が選択されていません" }

end

app/controllers/advertisings_controller.rb
class AdvertisingsController < ApplicationController

  def index
    @inc_account_id = params[:id]
    @advertisings = Advertising.all
  end

  def show
    @advertising = Advertising.find(params[:id])
  end

  def new
    @inc_account_id = params[:id]
    @advertising = Advertising.new
  end

  def create
    @inc_account_id = advertising_params[:id]
    upload_file = advertising_params[:file]
    advertising = {}
    if upload_file != nil
      advertising[:inc_account_id] = @inc_account_id
      advertising[:advertise_info] = advertising_params[:advertise_info]
      advertising[:image] = upload_file.read
      advertising[:content_type] = upload_file.content_type
      advertising[:contract_date] = Date.today
    end
    @advertising = Advertising.new(advertising)
    if @advertising.save
      @advertisings = Advertising.all
      render action: "index"
    else
      @message = "広告を保存できませんでした"
      render action: "new"
    end
  end

  def show_image
    @advertising = Advertising.find(params[:id])
    send_data @advertising.image, :type => @advertising.content_type, :disposition => 'inline'
  end

  private
    def advertising_params
      params.require(:advertising).permit(:id, :advertise_info, :file)
    end
end

app/helpers/advertisings_helper.rb
module AdvertisingsHelper
end

app/views/advertisings/index.html.erb
<%= render 'shared/library' %>
<%= render 'shared/incmenu' %>

<div class="container-fluid" style="margin:20px;"><div class="row">
  <div align="right">
    <%= button_to "広告登録", new_advertising_path, method: :get, params: { id: @inc_account_id }, class: "btn btn-success", style: "margin:5px;"%></div>
    <ul class="nav nav-tabs">
     <li><a href="/housings?id=<%= @inc_account_id %>">物件</a></li>
     <li class="active"><a href="/advertisings?id=<%= @inc_account_id %>">広告</a></li>
    </ul>
    <div class="container">
      <table class="table">
        <thead>
        <tr>
          <th>広告情報</th>
          <th>イメージ</th>
          <th>契約更新日</th>
        </tr>
        </thead>

        <tbody>
        <% @advertisings.each do |advertising| %>
            <tr>
              <td><%= advertising.advertise_info %></td>
              <td><%= image_tag show_image_advertising_path(advertising), size: "150x150" %></td>
              <td><%= advertising.contract_date %></td>
              <td><%= link_to '詳細', '#', class: "btn btn-warning" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
</div></div>

app/views/advertisings/new.html.erb
<%= form_for(@advertising) do |f| %>
  <% if @message %>
  <font color="red"><%= @message %></font>
  <% end %>
  <%= f.hidden_field :id, value: @inc_account_id %>
  <%= f.text_field :advertise_info, :placeholder => "広告情報" %>
  <%= f.file_field :file, accept: "image/*" %>
  <%= f.submit "Upload" %>
<% end %>

app/views/advertisings/show.html.erb
<%= image_tag show_image_advertising_path(@advertising),class: "large-img" %>