config/routes.rb
Rails.application.routes.draw do
  root :to => 'search#form'

  get 'search' => 'search#form'
  post 'search/form'
  get 'search/form'
  post 'search/show'
  get 'search/show' => 'search#form'
  post 'search/detail'
  get 'search/detail' => 'search#form'
  post 'search/logout'
  get 'search/logout' => 'search#form'

  get '/users/login' => 'users#login'
  post '/users/auth' => 'users#auth'
  get '/users/new' => 'users#new'
  post '/users/edit' => 'users#edit'
  post '/users/update' => 'users#update'
  delete '/users/destroy/:id' => 'users#destroy'
  get  '/users/avaliable/:link_pass' => 'users#avaliable'
  post '/users/confirm' => 'users#confirm'
  post '/users/complete' => 'users#complete'

  get '/inc_accounts/login' => 'inc_accounts#login'
  get '/inc_accounts/new' => 'inc_accounts#new'
  post '/inc_accounts/edit' => 'inc_accounts#edit'
  post '/inc_accounts/update' => 'inc_accounts#update'
  delete '/inc_accounts/destroy/:id' => 'inc_accounts#destroy'
  post '/inc_accounts/auth' => 'inc_accounts#auth'
  post '/inc_accounts/logout' => 'inc_accounts#logout'
  get  '/inc_accounts/avaliable/:link_pass' => 'inc_accounts#avaliable'
  post '/inc_accounts/confirm' => 'inc_accounts#confirm'
  post '/inc_accounts/complete' => 'inc_accounts#complete'

  get '/housing_databases/showTables/:id' => 'housing_databases#showTables', as: 'housing_databases_showTables'
 get '/housing_databases/registerDatabases/:id' => 'housing_databases#registerDatabases', as: 'housing_databases_registerDatabases'
 get '/housing_databases/detail/:id' => 'housing_databases#detail', as: 'housing_databases_detail'
 get '/housing_databases/editDatabases/:id' => 'housing_databases#editDatabases',as: 'housing_databases_editDatabases'
 get '/housing_databases/:id/image/' => 'housing_databases#image',as: 'housing_databases_image'
 post '/housing_databases/registerDatabases/:id' => 'housing_databases#create'
 patch '/housing_databases/editDatabases/:id' => 'housing_databases#update'
 delete '/housing_databases/details/:id' => 'housing_databases#destroy',as:'housing_databases_destroy'

 get '/advertising_databases/showTables/:id' => 'advertising_databases#showTables',as:'advertising_databases_showTables'
 get '/advertising_databases/registerDatabases/:id' => 'advertising_databases#registerDatabases',as:'advertising_databases_registerDatabses'
 get '/advertising_databases/details/:id' => 'advertising_databases#details', as: 'advertising_databases_details'
 get '/advertising_databases/editDatabases/:id' => 'advertising_databases#editDatabases',as: 'advertising_databases_editDatabases'
 get '/advertising_databases/:id/image/' => 'advertising_databases#image',as: 'advertising_databases_image'
 post '/advertising_databases/registerDatabases/:id' => 'advertising_databases#create'
 patch '/advertising_databases/editDatabases/:id' => 'advertising_databases#update'
 delete '/advertising_databases/showTables/:id' => 'advertising_databases#destroy',as:'advertising_databases_destroy'

  get '/store/registerStores/:id' => 'store#registerStores',as: 'registerStores'
  get '/store/showStores/:id' => 'store#showStores',as:'showStores'
  get '/store/editStores/:id' => 'store#editStores',as:'editStores'
  post '/store/registerStores/:id' => 'store#create'
  patch '/store/editStores/:id' => 'store#update'
  delete '/store/showStores/:id' => 'store#destroy',as:'store_destroy'

  resources :search do
    member { get :image }
  end
  resources :advertising_databases do
      member do
        get 'show_image'
      end
  end

end

app/controllers/search_controller.rb
#conding: utf-8

############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/11/29 ;
# author   = Kenta Togashi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################

class SearchController < ApplicationController
  def form

    if params[:user_name]!=nil && User.find_by(user_name: params[:user_name])!=nil && User.find_by(user_name: params[:user_name]).avaliable!=false
      @user_name = params[:user_name]
    end

      #広告取得
      advertisings=Advertising.all
      @advertisings=[]
      if advertisings.length>0 then
          (0..1).each{|num|
              @advertisings[num]=advertisings[rand(0..advertisings.length-1)]
          }
      end
  end

  def show
      @user_name=params[:user_name]
      destination=params[:destination]
      @destination=[]
      @destination[0]=destination['d1']
      @destination[1]=destination['d2']
      @destination[2]=destination['d3']
      @destination[3]=destination['d4']
      @destination[4]=destination['d5']
      @filter=destination['filter']
      @slope=params[:slope]
      keyword=params[:keyword]
      if keyword==nil then keyword="" end #キーワードがnilなら空にする
      @keyword=keyword
      @max_value = 0;
      if defined?(params[:show]['sort']) then @sort=params[:show]['sort'] else @sort="距離が近い順" end
      @page=params[:page].to_i

      #選択した施設が重複していないかチェック
      @error=false
      for i in 0..3 do
          for j in 1..4 do
              if i<j && @destination[i]==@destination[j] then
                  @error=true
              end
          end
      end

      #住宅取得
      @housings=[]
      @options=[] #住宅の付随情報
      if session[@user_name]!=nil then user=User.select("id").where("user_name = :user_name",user_name: @user_name)
      else user=nil end
      housings=Housing.all
      housings.each{|housing|
              if housing.vacancy=="" then next end #空き部屋がない住宅は飛ばす
              
              #お気に入り登録されているか調べる
              fav_flag=0
              if user!=nil then
                  favorite=Favorite.where("user_id = :user_id and housing_id = :housing_id",user_id: user[0].id,housing_id: housing.id)
                  if favorite.length>0 then fav_flag=1 end
              else fav_flag=0 end
              
              #お気に入りリスト表示の場合、お気に入り登録されていない奴は飛ばす
              if @slope!="yes" && @slope!="no" && fav_flag==0 then next end
              
              flag=0
              if keyword!="" then #絞り込みあり
                  keyword=keyword.gsub("　"," ")
                  keywords=keyword.split(" ") #複数あるキーワードを分割
                  flags=0
                  keywords.each{|keyword|
                      #見出し情報から
                      if housing.housing_type.include?(keyword) then flags+=1 end
                      if housing.street_address.include?(keyword) then flags+=1 end
                      if housing.direction.include?(keyword) then flags+=1 end
                      if housing.layout.include?(keyword) then flags+=1 end
                      #詳細
                      if housing.detail.include?(keyword) then flags+=1 end
                      if housing.structure.include?(keyword) then flags+=1 end
                      if housing.trading_aspect.include?(keyword) then flags+=1 end
                      if housing.vacancy.include?(keyword) then flags+=1 end
                      
                      #お気に入り登録されていないもの
                      if keyword=="お気に入り以外"||keyword=="お気に入りいがい"||keyword=="おきに入り以外"||keyword=="おきに入りいがい"||keyword=="お気にいり以外"||keyword=="お気にいりいがい"||keyword=="おきにいり以外"||keyword=="おきにいりいがい" then
                          if fav_flag==0 then flags+=1 end
                      #お気に入り登録されているもの
                      elsif keyword=="お気に入り"||keyword=="おきに入り"||keyword=="お気にいり"||keyword=="おきにいり"||keyword=="オキニイリ"||keyword=="okiniiri"||keyword=="favorite"||keyword=="favorites" then
                          if fav_flag==1 then flags+=1 end
                      end
                      
                  }
                  if keywords.length==flags then flag=1 end #全てひっかかればOK
                  @keyword=keyword
              else
                  flag=1
              end
              
              if flag==1 then #ヒットしたら登録
                  @housings.push(housing)
                  @options.push({"favorite" => fav_flag})
              end
      }

      #距離情報取得
      @distances=[]
      dis_len=0
      @housings.each{|housing|
          @distances[dis_len]={"id" => dis_len, "value" => 0}
          (0..4).each{|num|
              facilities=Facility.where("name like ?","("+@destination[num]+")%") #候補一覧取得
              distances=[]
              facilities.each{|facility| #候補との距離取得
                  distance=Distance.where("housing_id = :housing_id and facility_id = :facility_id",housing_id: housing.id,facility_id: facility.id).order("distance")
                  distances.push(distance[0])
              }
              min_index=0 #一番近い施設
              min_value=distances[0].distance #最小値
              index=0
              distances.each{|distance|
                  if distance.distance<min_value then #より近い施設発見
                      min_index=index
                      min_value=distance.distance
                  end
                  index+=1
              }

              @distances[dis_len][@destination[num]]={"value" => min_value , "facility" => facilities[min_index] }
          }
          dis_len+=1
      }

      #評価値決定
      @distances.each{|distance|
          if @slope=='yes' then #坂を気にする
              (0..4).each{|num|
                  distance[@destination[num]]["value"]**=1.1
              }
          end

          if @filter=="4" then
            distance["value"]=distance[@destination[0]]["value"]+distance[@destination[1]]["value"]*0.7+distance[@destination[2]]["value"]*0.3+distance[@destination[3]]["value"]*0.1
          elsif @filter=="3" then
            distance["value"]=distance[@destination[0]]["value"]+distance[@destination[1]]["value"]*0.7+distance[@destination[2]]["value"]*0.3
          elsif @filter=="2" then
            distance["value"]=distance[@destination[0]]["value"]+distance[@destination[1]]["value"]*0.7
          elsif @filter=="1" then
            distance["value"]=distance[@destination[0]]["value"]
          else
            @filter="5"
            distance["value"]=distance[@destination[0]]["value"]+distance[@destination[1]]["value"]*0.7+distance[@destination[2]]["value"]*0.3+distance[@destination[3]]["value"]*0.1+distance[@destination[4]]["value"]*0.01
          end
      }

      #並べ替え
      if @sort=="距離が近い順" then
        @distances.sort!{|a, b| a["value"] <=> b["value"] }
      elsif @sort=="賃料が安い順" then
        @distances.sort!{|a, b| @housings[a["id"]].rent <=> @housings[b["id"]].rent }
      elsif @sort=="賃料が高い順" then
        @distances.sort!{|a, b| @housings[b["id"]].rent <=> @housings[a["id"]].rent }
      elsif @sort=="面積が広い順" then
        @distances.sort!{|a, b| @housings[b["id"]].area <=> @housings[a["id"]].area }
      elsif @sort=="人気が高い順" then
        @distances.sort!{|a, b| @housings[b["id"]].favorites <=> @housings[a["id"]].favorites }
      elsif @sort=="閲覧が多い順" then
        @distances.sort!{|a, b| @housings[b["id"]].views <=> @housings[a["id"]].views }
      end

      #最も大きい評価値を調べる
      @distances.each{|distance|
        (0..4).each{|num|
          if @max_value < distance[@destination[num]]["value"]
            @max_value = distance[@destination[num]]["value"]
          end
        }
      }
      
      #ページ情報取得
      len=@distances.length-1
      if len<0 then len=0 end
      @max_page=(len/10)+1 #最大ページ番号
      if @page==nil then @page=1 #デフォルトは1
      elsif @page<1 then @page=1 #最小1
      elsif @page>@max_page then @page=@max_page end #最大は@max_page
      @dis_num=-1 #焦点を当てている物件番号

      #広告取得
      advertisings=Advertising.all
      @advertisings=[]
      if advertisings.length>0 then
          (0..4).each{|num|
              @advertisings[num]=advertisings[rand(0..advertisings.length-1)]
          }
      end

  end

  def detail
    @max_value=params[:max_value]
    @user_name=params[:user_name]
    housing_id=params[:housing_id]
    @distance={}
    @destination={}
    dis_num=0
    params[:distances].each{|key,value|
        @destination[dis_num]=key
        @distance[key]={ "value"=>value , "facility"=>Facility.find(params[:facilities][dis_num]) }
        dis_num+=1
    }
    @filter=params[:filter]
    @slope=params[:slope]
    @keyword=params[:keyword]
    @sort=params[:sort]
    @page=params[:page].to_i
    @user=User.select("id,user_name").where("user_name = :user_name",user_name: @user_name)
    @housing=Housing.find(housing_id)
    @inc=IncAccount.find(@housing.inc_account_id)
    @store=Store.find(@housing.store_id)

    #お気に入り登録
    fav=params[:fav]
    if session[@user_name]!=nil && fav=="登録" then
        favorite=Favorite.where("user_id = :user_id and housing_id = :housing_id",user_id: @user[0].id,housing_id: @housing.id)
        if favorite.length==0 then
            Favorite.create(:user_id=>@user[0].id , :housing_id=>@housing.id , :store_id=>@store.id , :inc_account_id=>@inc.id)
            @housing.favorites+=1 #お気に入り件数増やす
            @housing.save
        end
    end

    #お気に入り削除
    if session[@user_name]!=nil && fav=="削除" then
        favorite=Favorite.where("user_id = :user_id and housing_id = :housing_id",user_id: @user[0].id,housing_id: @housing.id)
        if favorite.length>0 then
            favorite[0].destroy
            @housing.favorites-=1 #お気に入り件数減らす
            @housing.save
        end
    end

    #お気に入り登録しているか調べる
    @favorite=[]
    if session[@user_name]!=nil then
        favorites=Favorite.where("user_id = :user_id and housing_id = :housing_id",user_id: @user[0].id,housing_id: @housing.id)
        if favorites.length>0 then @favorite.push(favorites[0]) end
    end

    #閲覧数カウント

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/detail.html.erb
<!-- ############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/11/30 ;
# author   = Kenta Togashi ;
# History  = ver1.0.0 ;
# end of specification ;
############################################################# -->

<%= render 'shared/library' %>
<%= render 'shared/menu' %>

<% housing=@housing %>

<div class="container-fluid"><div class="row">
<!-- 物件表示枠 -->
<div class="col-md-9">
<!-- 見出し -->
<% if @favorite.length==0 then %><div class="container-fluid" style="background: #ffeedd;">
<% else %><div class="container-fluid" style="background: #ffff99;"><% end %>
<div class="row">

<div class="col-sm-3">
    <%= image_tag(housing_databases_image_path(@housing.id), :class=>"img-responsive img-thumbnail") %>
</div>

<div class="col-sm-6" style="padding: 5px;"><table class="table table-bordered" style="background:#ffffff;"><tr>
  <td>
    <table class="table"><tr><td>
      <% rent_num=housing.rent/10000.to_f %>
      <p style="font-size: 18px; color: #ff0000; font-weight: bold;"><%= rent_num %>万円</p> <!-- 家賃 -->
      <div style="font-size: 13px;">
        管理費 <%= housing.administration_cost %>円 <!-- 管理費 -->
      </div>
    </td></tr><tr><td>
      <%= housing.housing_type %> <!-- タイプ -->
    </td></tr><tr><td>
      <%= housing.street_address %> <!-- 住所 -->
    </td></tr></table>
  </td>
  <td>
    <table class="table"><tr>
        <td>築年数　：</td><td>築<%= Date.today.year-housing.building_date.year %>年</td> <!-- 築年月 -->
    </tr><tr>
        <td>部屋向き：</td><td><%= housing.direction %></td> <!-- 方向 -->
    </tr><tr>
        <td>間取り　：</td><td><%= housing.layout %></td> <!-- 間取り -->
    </tr><tr>
        <td>専有面積：</td><td><% area_num=housing.area/10.to_f %><p><%= area_num %>m&sup2;</td> <!-- 面積 -->
    </tr></table>
  </td>
</tr></table></div>

<!-- グラフ -->
<div class="col-sm-3" style="padding:5px;">
  <center>
  <table  style="background:#ffffee;" bordercolor="#cc6633"><tr><td>
  <canvas id="chart" width="170" height="170">
  </canvas>
  </td></tr>
  <tr><td><center><b>距離得点：<%= 5.0-((@distance[@destination[0]]['value'].to_f+@distance[@destination[1]]['value'].to_f*0.7+@distance[@destination[2]]['value'].to_f*0.3+@distance[@destination[3]]['value'].to_f*0.1+@distance[@destination[4]]['value'].to_f*0.01)/@max_value.to_f).round(2) %>/5.00
  </b></center></td></tr>
  </table></div>
  <script>
    write_chart("chart",
      "<%= @destination[0] %>",
      "<%= @destination[1] %>",
      "<%= @destination[2] %>",
      "<%= @destination[3] %>",
      "<%= @destination[4] %>",
      Number("<%= @distance[@destination[0]]['value'].to_f %>"),
      Number("<%= @distance[@destination[1]]['value'].to_f %>"),
      Number("<%= @distance[@destination[2]]['value'].to_f %>"),
      Number("<%= @distance[@destination[3]]['value'].to_f %>"),
      Number("<%= @distance[@destination[4]]['value'].to_f %>"),
      Number("<%= @max_value.to_f %>"))
  </script>
  </center>


</div></div>
<div style="height:40px;"></div>

<!-- 詳細情報 -->
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">特徴</div>
    <div class="col-sm-10"><%= housing.detail %></div>
</div></div>
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">構造</div>
    <div class="col-sm-4"><%= housing.structure %></div>
    <div class="col-sm-2" style="background:#e5e5e5">階建</div>
    <div class="col-sm-4"><%= housing.floor %>階建</div>
</div></div>
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">空き部屋</div>
    <div class="col-sm-10"><%= housing.vacancy %></div>
</div></div>
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">敷金</div>
    <div class="col-sm-4"><%= housing.deposit %>円</div>
    <div class="col-sm-2" style="background:#e5e5e5">礼金</div>
    <div class="col-sm-4"><%= housing.recompense %>円</div>
</div></div>
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">保証金</div>
    <div class="col-sm-4"><%= housing.security_money %>円</div>
    <div class="col-sm-2" style="background:#e5e5e5">敷引</div>
    <div class="col-sm-4"><%= housing.shikibiki %>円</div>
</div></div>
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">損保</div>
    <div class="col-sm-4"><%= housing.insurance %>円</div>
    <div class="col-sm-2" style="background:#e5e5e5">駐車場</div>
    <div class="col-sm-4">
        <% if housing.parking>=0 then %><%= housing.parking %>円 <!-- 料金がある -->
        <% else %>なし<% end %> <!-- 駐車場なし -->
    </div>
</div></div>
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">取引態様</div>
    <div class="col-sm-10"><%= housing.trading_aspect %></div>
</div></div>
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">他初期費用</div>
    <div class="col-sm-10"><%= housing.another_cost %>円</div>
</div></div>
<div class="container-fluid" style="border: solid 1px #bbbbbb;"><div class="row">
    <div class="col-sm-2" style="background:#e5e5e5">最終更新日</div>
    <div class="col-sm-10">
        <%= housing.updated_at.year %>年<%= housing.updated_at.mon %>月<%= housing.updated_at.day %>日
    </div>
</div></div>
<div style="height:40px;"></div>

<!-- お気に入り登録ボタン -->
<% if session[@user_name]!=nil then %>
<%= form_tag('/search/detail', :method => :post) do %>
    <input type="hidden" name="user_name" value="<%= session[@user_name] %>" >
    <input type="hidden" name="housing_id" value="<%= @housing.id %>" >
    <input type="hidden" name="max_value" value="<%= @max_value %>" >
    <input type="hidden" name="filter" value="<%= @filter %>">
    <input type="hidden" name="slope" value="<%= @slope %>" >
    <input type="hidden" name="keyword" value="<%= @keyword %>" >
    <input type="hidden" name="sort" value="<%= @sort %>" >
    <input type="hidden" name="page" value="<%= @page %>">
    <% @distance.each{|key,value| %>
        <input type="hidden" name="distances[<%= key %>]" value=<%= value['value'] %> >
        <input type="hidden" name="facilities[]" value="<%= value['facility'].id %>" >
    <% } %>
    <div class="container-fluid"><div class="row"><div class="col-xs-12 text-center">
        <% if @favorite.length==0 then %>
            <input type="hidden" name="fav" value="登録" >
            <input type="submit" value="お気に入り登録" class="btn btn-info">
        <% else %>
            <input type="hidden" name="fav" value="削除" >
            <input type="submit" value="お気に入り削除" class="btn btn-info">
        <% end %>
    </div></div></div>
<% end %>
<div style="height:20px;"></div>
<% end %>

<!-- お問い合わせ先 -->
<div style="border: ridge 10px #ffdee7; background: #ffdee7; padding: 10px;">
    <div style="font-weight: bold;">問い合わせ</div>
    <%= @inc.inc_name+@store.store_name %><br>
    住所：<%= @store.street_address %><br>
    TEL：<%= @inc.phone_num %><br>
    メールアドレス：<%= @inc.mail_address %><br>
</div>
<div style="height:20px;"></div>

<!-- 写真
<table style="min-width: 630px; max-width: 630px;"><tr><td style="border: solid 1px #000000;">
<% (0..10).each{|num| %>
    <img src="http://jsrun.it/assets/b/K/I/l/bKIlt.png" alt="写真" width="200" height="200">
<% } %>
</td></tr></table>
-->

<!-- 地図 -->
<script>
window.onload=function(){
var map=new GMaps({
    div: "#map",
    lat: 35.710285,
    lng: 139.77714,
    zoom: 15
});
var housing_latlng;
GMaps.geocode({ //住宅にマークをつける
    address: "<%= housing.street_address %>",
    callback: function(results,status){
        if(status=='OK'){
            housing_latlng = results[0].geometry.location;
            map.setCenter(housing_latlng.lat(),housing_latlng.lng());
            map.addMarker({
                icon: "https://maps.google.com/mapfiles/ms/icons/green-dot.png",
                lat: housing_latlng.lat(),
                lng: housing_latlng.lng(),
                infoWindow: {content: '対象物件'}
            });
        }
    }
});
<% @distance.each{|key,value| %>
    GMaps.geocode({ //施設にマークをつける
        address: "<%= value['facility'].street_address %>",
        callback: function(results,status){
            if(status=='OK'){
                var latlng = results[0].geometry.location;
                map.addMarker({
                    icon: "https://maps.google.com/mapfiles/ms/icons/blue-dot.png",
                    lat: latlng.lat(),
                    lng: latlng.lng(),
                    infoWindow: {content: '<%= value['facility'].name %><br>移動距離：<%= value['value'] %>m<br>徒歩所要時間：<%= value['value'].to_i/80 %>分'}
                });
                map.drawRoute({
                    origin: [housing_latlng.lat(), housing_latlng.lng()],
                    destination: [latlng.lat(), latlng.lng()],
                    travelMode: 'walking',
                    strokeColor: '#0000ff',
                    strokeOpacity: 0.6,
                    strokeWeight: 3
                });
            }
        }
    });
<% } %>
geocoding=function(address){
    if(address==""){return;} //入力値が空なら処理しない
    GMaps.geocode({
        address: "茨城県日立市"+address,
        callback: function(results, status){
            if(status=='OK'){
                var latlng = results[0].geometry.location;
                map.setCenter(latlng.lat(), latlng.lng());
                map.addMarker({
                    lat: latlng.lat(),
                    lng: latlng.lng(),
                    infoWindow: {content: address}
                });
                map.drawRoute({
                    origin: [housing_latlng.lat(), housing_latlng.lng()],
                    destination: [latlng.lat(), latlng.lng()],
                    travelMode: 'walking',
                    strokeColor: '#ff0000',
                    strokeOpacity: 0.6,
                    strokeWeight: 3
                });
            }
        }
    });
};
};
</script>

<form name="geocoding_form">
<div class="container-fluid"><div class="row"><div class="col-xs-12">
    茨城県日立市
    <textarea name="address" cols="25" rows="2" maxlength="50" placeholder="調べたい施設名や住所(町名から)を入力"></textarea>
    <button type=button class="btn btn-success" onclick="geocoding(document.geocoding_form.address.value);">検索</button>
</div></div></div>
</form>
<div style="height:10px;"></div>

<div class="container-fluid"><div class="row">
<div class="col-sm-8">
    <div id="map" style="width:450px; height:450px;"></div> <!-- 地図表示 -->
    <div style="height:5px;"></div>
    <p style="color:#ff0000;">※ルートが表示されない場合は、ページを更新してください。</p>
</div>
<div class="col-sm-4">
    <table class="table table-bordered">
        <tr><th>施設名</th><th>距離</th></tr>
        <% @distance.each{|key,value| %>
            <tr><td><%= value['facility'].name %></td><td><%= value['value'] %>m</td></tr>
        <% } %>
    </table>
</div>
</div></div>
<div style="height:20px;"></div>

<!-- 物件一覧に戻るボタン -->
<%= form_tag('/search/show', :method => :post) do %>
    <input type="hidden" name="user_name" value="<%= @user_name %>" >
    <input type="hidden" name="destination[d1]" value="<%= @destination[0] %>">
    <input type="hidden" name="destination[d2]" value="<%= @destination[1] %>">
    <input type="hidden" name="destination[d3]" value="<%= @destination[2] %>">
    <input type="hidden" name="destination[d4]" value="<%= @destination[3] %>">
    <input type="hidden" name="destination[d5]" value="<%= @destination[4] %>">
    <input type="hidden" name="destination[filter]" value="<%= @filter %>">
    <input type="hidden" name="slope" value="<%= @slope %>">
    <input type="hidden" name="keyword" value="<%= @keyword %>">
    <input type="hidden" name="show[sort]" value="<%= @sort %>">
    <input type="hidden" name="page" value="<%= @page %>">
    <% if @slope=="yes" || @slope=="no" then %><input type="submit" value="物件一覧に戻る" class="btn btn-primary">
    <% else %><input type="submit" value="お気に入り物件一覧に戻る" class="btn btn-default"><% end %>
    <div style="height:40px;"></div>
<% end %>

<div style="height:20px;"></div>
</div>

<!-- 広告枠 -->
<div class="col-md-3">
<div style="height:40px;"></div>
広告<br>
<table class="table">
<% @advertisings.each{|advertising| %>
    <tr><th><%= image_tag(advertising_databases_image_path(advertising.id), :size => '150x150') %></td></tr>
<% } %>
</table>
</div>

</div></div>