config/routes.rb
Rails.application.routes.draw do
  root :to => 'search#form'

  get 'search' => 'search#form'
  post 'search/form'
  get 'search/form'
  post 'search/show'
  get 'search/show' => 'search#form'
  post 'search/detail'
  get 'search/detail' => 'search#form'
  post 'search/logout'
  get 'search/logout' => 'search#form'

  get '/users/login' => 'users#login'
  post '/users/auth' => 'users#auth'
  get '/users/new' => 'users#new'
  post '/users/edit' => 'users#edit'
  post '/users/update' => 'users#update'
  delete '/users/destroy/:id' => 'users#destroy'
  get  '/users/avaliable/:link_pass' => 'users#avaliable'
  post '/users/confirm' => 'users#confirm'
  post '/users/complete' => 'users#complete'

  get '/inc_accounts/login' => 'inc_accounts#login'
  get '/inc_accounts/new' => 'inc_accounts#new'
  post '/inc_accounts/edit' => 'inc_accounts#edit'
  post '/inc_accounts/update' => 'inc_accounts#update'
  delete '/inc_accounts/destroy/:id' => 'inc_accounts#destroy'
  post '/inc_accounts/auth' => 'inc_accounts#auth'
  post '/inc_accounts/logout' => 'inc_accounts#logout'
  get  '/inc_accounts/avaliable/:link_pass' => 'inc_accounts#avaliable'
  post '/inc_accounts/confirm' => 'inc_accounts#confirm'
  post '/inc_accounts/complete' => 'inc_accounts#complete'

  get '/housing_databases/showTables/:id' => 'housing_databases#showTables', as: 'housing_databases_showTables'
 get '/housing_databases/registerDatabases/:id' => 'housing_databases#registerDatabases', as: 'housing_databases_registerDatabases'
 get '/housing_databases/detail/:id' => 'housing_databases#detail', as: 'housing_databases_detail'
 get '/housing_databases/editDatabases/:id' => 'housing_databases#editDatabases',as: 'housing_databases_editDatabases'
 get '/housing_databases/:id/image/' => 'housing_databases#image',as: 'housing_databases_image'
 post '/housing_databases/registerDatabases/:id' => 'housing_databases#create'
 patch '/housing_databases/editDatabases/:id' => 'housing_databases#update'
 delete '/housing_databases/details/:id' => 'housing_databases#destroy',as:'housing_databases_destroy'

 get '/advertising_databases/showTables/:id' => 'advertising_databases#showTables',as:'advertising_databases_showTables'
 get '/advertising_databases/registerDatabases/:id' => 'advertising_databases#registerDatabases',as:'advertising_databases_registerDatabses'
 get '/advertising_databases/details/:id' => 'advertising_databases#details', as: 'advertising_databases_details'
 get '/advertising_databases/editDatabases/:id' => 'advertising_databases#editDatabases',as: 'advertising_databases_editDatabases'
 get '/advertising_databases/:id/image/' => 'advertising_databases#image',as: 'advertising_databases_image'
 post '/advertising_databases/registerDatabases/:id' => 'advertising_databases#create'
 patch '/advertising_databases/editDatabases/:id' => 'advertising_databases#update'
 delete '/advertising_databases/showTables/:id' => 'advertising_databases#destroy',as:'advertising_databases_destroy'

  get '/store/registerStores/:id' => 'store#registerStores',as: 'registerStores'
  get '/store/showStores/:id' => 'store#showStores',as:'showStores'
  get '/store/editStores/:id' => 'store#editStores',as:'editStores'
  post '/store/registerStores/:id' => 'store#create'
  patch '/store/editStores/:id' => 'store#update'
  delete '/store/showStores/:id' => 'store#destroy',as:'store_destroy'

  resources :search do
    member { get :image }
  end
  resources :advertising_databases do
      member do
        get 'show_image'
      end
  end

end

app/controllers/advertising_databases_controller.rb
############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################

class AdvertisingDatabasesController < DatabasesController
  def showTables
    @inc_account_id = params[:id]
    @inc_account = IncAccount.find(@inc_account_id)
    @advertising = Advertising.where(inc_account_id: @inc_account_id)
  end

  def image
    @advertising = Advertising.find(params[:id])
    send_data(@advertising.image, :type => 'image/jpeg', disposition: :inline)
  end

  def registerDatabases
    @inc_account_id = params[:id]
    @advertising = Advertising.new
  end

  def editDatabases
    @advertising = Advertising.find(params[:id])
  end

  def deleteDatabases
    @inc_account_id = params[:id]
  end

  def details
    @advertising = Advertising.find(params[:id])
    @inc = IncAccount.find(@advertising.inc_account_id)
  end

  def create
    @inc_account = IncAccount.find(params[:id])
    @inc_account_id = params[:id]

    # upload_file = params.require(:image)
    # adv = {}
    # if upload_file != nil
    #   adv[:advertise_info] = params[:advertise_info]
    #   adv[:image] = upload_file.read
    #   adv[:inc_account_id] = params[:id]
    #   adv[:contract_date] = Date.today
    # end
    # @advertising = Advertising.new(adv)

    @advertising = Advertising.new
    @advertising.advertise_info = params[:advertise_info]
    @advertising.inc_account_id = @inc_account_id
    if params[:image].present?
      @advertising.image = params[:image].read
    end

    if @advertising.save
      @advertising = Advertising.where(inc_account_id: @inc_account_id)
      render :action => "showTables"
    else
      render :action => 'registerDatabases'
    end

  end

  def update
    @advertising = Advertising.find(params[:id])
    @inc = IncAccount.find(@advertising.inc_account_id)

    @advertising.advertise_info = params[:advertise_info]
    if params[:image].present?
      @advertising.image = params[:image].read
    end

    if @advertising.save
      redirect_to advertising_databases_showTables_path(@advertising.inc_account_id), notice: "広告情報の編集を完了しました"
    else
      render :action => 'editDatabases'
    end

  end

  def destroy
    @advertising = Advertising.find(params[:id])
    @inc_account_id = IncAccount.find(@advertising.inc_account_id).id
    @advertising.destroy
    redirect_to advertising_databases_showTables_path(@inc_account_id)
  end

  private
  def authenticate_user
    @inc_account_id = params[:id]
    if session[@inc_account_id]==nil || session[@inc_account_id]==''
      #広告取得
      advertisings=Advertising.all
      @advertisings=[]
      if advertisings.length>0 then
          (0..1).each{|num|
              @advertisings[num]=advertisings[rand(0..advertisings.length-1)]
          }
      end
      render :template => "search/form"
    end
  end
end

app/helpers/advertising_databases_helper.rb
module AdvertisingDatabasesHelper
end

app/views/advertising_databases/detail.html.erb
<!--############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################-->

<%= render 'shared/library' %>
<%= render 'shared/incmenu' %>

<table>
  <tbody>
  <tr><td>広告情報</td> <td><%= @advertising.advertise_info%></td> </tr>
  <tr><td>広告画像</td>  <td><%= image_tag(advertising_databases_image_path(@advertising.id), :size => '100x100')%></td> </tr>
  <tr><td>広告画像URL</td>  <td><%= @advertising.image_content_type%></td> </tr>
  <tr><td>契約更新日</td>  <td><%= @advertising.contract_date%></td> </tr>
  </tbody>
</table>

<%= link_to '編集', advertising_databases_editDatabases_path(@advertising.id) %>
<%= link_to '削除', advertising_databases_destroy_path(@advertising.id),method: 'delete',"data-confirm" => "本当に削除しますか？" %>
<%= link_to '一覧へ戻る', advertising_databases_showTables_path(@inc.id)%>

app/views/advertising_databases/editDatabases.html.erb
<!--############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################-->

<%= render 'shared/library' %>
<%= render 'shared/incmenu' %>

<%= form_tag advertising_databases_editDatabases_path(@advertising.id), method: 'patch', multipart: true do%>
    <table>

      <tbody>
      <tr><td>広告情報</td>  </tr>
      <tr><td><%= text_field_tag :advertise_info,@advertising.advertise_info, :placeholder => "広告情報" %></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @advertising.errors.messages[:advertise_info] %></font></td><tr>
      <tr><td>画像</td>  </tr>
      <tr><td><%= file_field_tag 'image' ,:accept => "image/png,image/gif,image/jpeg"%></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @advertising.errors.messages[:image] %></font></td><tr>

      </tbody>
    </table>

    <%= submit_tag "編集","data-confirm" => "編集を行いますか？" %>
<% end %>

app/views/advertising_databases/registerDatabases.html.erb
<!--############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################-->

<%= render 'shared/library' %>
<%= render 'shared/incmenu' %>

<%= form_tag('/advertising_databases/showTables', :method => :get) do %>
  <input type="hidden" name="inc_account_id" value="<%= @inc_account_id %>" >
  <input type="submit" value="戻る" formaction='/advertising_databases/showTables/<%= @inc_account_id %>' formmethod='get' class="btn btn-warning">
<% end %>

<%= form_tag advertising_databases_registerDatabses_path(params[:id]), multipart: true do%>
    <table>

      <tbody>
      <tr><td>広告情報</td> </tr>
      <tr><td><%= text_field_tag :advertise_info,@advertising.advertise_info, :placeholder => "広告情報" %></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @advertising.errors.messages[:advertise_info] %></font></td><tr>
      <tr><td>画像</td> </tr>
      <tr><td><%= file_field_tag 'image',:accept => "image/png,image/gif,image/jpeg" %></td></tr>
      <tr height="30"><td colspan="2"><font color="red">　　<%= @advertising.errors.messages[:image] %></font></td><tr>

      </tbody>
    </table>

    <%= submit_tag "登録" ,"data-confirm" => "登録を行いますか？"%>
<% end %>

app/views/advertising_databases/showTables.html.erb
<!--############################################################
# specificat on ;
# name     = Good Measure ;
# note     = ;
# date     = 2015/12/6 ;
# author   = Nishi ;
# History  = ver1.0.0 ;
# end of specification ;
#############################################################-->

<%= render 'shared/library' %>
<%= render 'shared/incmenu' %>

<div style="#999999">
<div class="container-fluid" style="margin:20px;"><div class="row">
  <ul class="nav nav-tabs">
   <li><a href="/housing_databases/showTables/<%= @inc_account.id %>">物件</a></li>
   <li class="active"><a href="/advertising_databases/showTables/<%= @inc_account.id %>">広告</a></li>
    <li><a href="/store/showStores/<%= @inc_account.id %>">店舗</a></li>
  </ul>
    <div align="right"><%= button_to "広告登録", advertising_databases_registerDatabses_path(@inc_account_id), method: :get, class: "btn btn-success", style: "margin:5px;"%></div>
  <div class="container">
    <table class="table">
      <thead>
      <tr>
        <th>広告情報<%= @mexx %></th>
        <th>イメージ</th>
        <th>契約更新日</th>
      </tr>
      </thead>

      <tbody>
      <% @advertising.each do |info| %>
          <tr>
            <td><%= info.advertise_info %></td>
            <td><%= image_tag(advertising_databases_image_path(info.id), :size => '100x100') %></td>
            <td><%= info.contract_date %></td>
            <td><%= link_to '編集', advertising_databases_editDatabases_path(info.id), class: "btn btn-warning" %> <%= link_to '削除', advertising_databases_destroy_path(info.id),method: 'delete', class: "btn btn-warning" ,"data-confirm" => "本当に削除しますか？"%></td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div></div></div>